name: notify-phpcfdi-cfdi-to-json
on:
  workflow_dispatch:
  push:
    paths:
      - 'complementos_v1.json'
    branches:
      - master

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      # see https://github.com/marketplace/actions/repository-dispatch
      - name: "Notify phpcfdi/cfdi-to-json"
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: phpcfdi/cfdi-to-json
          event-type: sat-ns-registry-update
